### ISSUE TITLE
futurerestore-s0uthwest fail fetch from github.

### ISSUE THREAD

**Issue by riotdream** [stek29/homebrew-idevice#15]
| => brew reinstall futurerestore-s0uthwest
==> Reinstalling stek29/idevice/futurerestore-s0uthwest 
==> Cloning https://github.com/s0uthwest/futurerestore.git
Cloning into '/Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git'...
==> Checking out revision 536fee9e67dbc2842b2e461bb0d23cfd0f6cf903
Note: checking out '536fee9e67dbc2842b2e461bb0d23cfd0f6cf903'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 536fee9 Update ReadMe
Submodule 'external/idevicerestore' (https://github.com/s0uthwest/idevicerestore.git) registered for path 'external/idevicerestore'
Submodule 'external/img4tool' (https://github.com/s0uthwest/img4tool.git) registered for path 'external/img4tool'
Submodule 'external/tsschecker' (https://github.com/s0uthwest/tsschecker.git) registered for path 'external/tsschecker'
Cloning into '/Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/idevicerestore'...
Cloning into '/Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/img4tool'...
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.

**Comment by stek29** [comment]
it was removed from the repo, use futurerestore
sorry for long wait.
