### ISSUE TITLE
idevicerestore won't compile.

### ISSUE THREAD

**Issue by riotdream** [stek29/homebrew-idevice#16]
| => PKG_CONFIG_PATH="/usr/local/Cellar/libzip/1.6.1/lib/pkgconfig/"
| => brew install idevicerestore
Updating Homebrew...
==> Installing idevicerestore from stek29/idevice
==> Cloning https://github.com/libimobiledevice/idevicerestore.git
Updating /Users/suzughia/Library/Caches/Homebrew/idevicerestore--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at d1cb6bf Support stopping at restore mode
==> ./autogen.sh --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/ideviceresto
Last 15 lines from /Users/suzughia/Library/Logs/Homebrew/idevicerestore/01.autogen.sh:
checking pkg-config is at least version 0.9.0... yes
checking for libirecovery >= 0.2.0... yes
checking for libimobiledevice-1.0 >= 1.2.1... yes
checking for libplist >= 1.12... yes
checking for libzip >= 0.8... no
configure: error: Package requirements (libzip >= 0.8) were not met:

No package 'libzip' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libzip_CFLAGS
and libzip_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/stek29/homebrew-idevice/issues
---------------------------------------------------------------------------------
| => brew info libzip
libzip: stable 1.6.1 (bottled)
C library for reading, creating, and modifying zip archives
https://libzip.org/
Conflicts with:
  libtcod (because libtcod, libzip and minizip2 install a `zip.h` header)
  minizip2 (because libtcod, libzip and minizip2 install a `zip.h` header)
/usr/local/Cellar/libzip/1.6.1 (135 files, 582.2KB) *
  Poured from bottle on 2020-05-14 at 13:54:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libzip.rb
==> Dependencies
Build: cmake ‚úî
==> Analytics
install: 50,173 (30 days), 164,465 (90 days), 582,719 (365 days)
install-on-request: 6,058 (30 days), 16,894 (90 days), 47,357 (365 days)
build-error: 0 (30 days)

**Comment by stek29** [comment]
thanks!
