### ISSUE TITLE
No package libplist found when installing tsschecker

### ISSUE THREAD

**Issue by maenpaa24** [stek29/homebrew-idevice#19]
When installing the tsschecker formula, the package libplist is not found although a newer version than required is already installed.

This is the output from brew install tsschecker:

> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for libplist >= 2.0.0... no
> configure: error: Package requirements (libplist >= 2.0.0) were not met:
> 
> No package 'libplist' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables libplist_CFLAGS
> and libplist_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
>   https://github.com/stek29/homebrew-idevice/issues

This is the output from brew install libplist:

> Updating Homebrew...
> Warning: libplist 2.2.0 is already installed and up-to-date
> To reinstall 2.2.0, run `brew reinstall libplist`

**Comment by teelekkung** [comment]
seem like autogen doesn't see libplist. me has already install and on bigger as well ,future restore can't compile with same error as you

**Comment by maenpaa24** [comment]
The issue might not lie on @stek29's side but on the latest released stable version of tsschecker. I am saying this because if you install the HEAD version it works. I guess I can close the issue.
