### ISSUE TITLE
formula for supraudit breaks brew search

### ISSUE THREAD

**Issue by resistor4u** [stek29/homebrew-idevice#2]
I have little knowledge of Ruby, but I think something in your formula for supraudit breaks `brew search`. 

Installing it gives `Error: No such file or directory @ rb_sysopen - /usr/local/Caskroom/supraudit/latest/tmp/LICENSE` and some other tracebacks. Uninstalling it does the same.

Regardless of whether supraudit is installed or uninstalled, `brew search` anything returns with the same error. To get brew search to work at all, I had to un- and reinstall cask, then

```
sudo mkdir /usr/local/Caskroom
sudo chown -R $(whoami) $(brew --prefix)/*
mkdir -pv /usr/local/Caskroom/supraudit/latest/tmp
touch /usr/local/Caskroom/supraudit/latest/tmp/LICENSE
```

Doing this gets brew search to work, but my thought is it’s a temporary fix. Indeed, the reinstallation process deletes `/usr/local/Caskroom/surpaudit`.

**Comment by stek29** [comment]
@resistor4u wow, thanks. That's really weird.
