### ISSUE TITLE
idevicerestore doesn't compile

### ISSUE THREAD

**Issue by InternalLoss** [stek29/homebrew-idevice#25]
After running `brew tap stek29-idevice`, trying to install idevicerestore:
```
==> ./autogen.sh --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/idevicerestore/git0
Last 15 lines from /Users/billy/Library/Logs/Homebrew/idevicerestore/01.autogen.sh:
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libirecovery-1.0 >= 1.0.1... no
configure: error: Package requirements (libirecovery-1.0 >= 1.0.1) were not met:

Requested 'libirecovery-1.0 >= 1.0.1' but version of libirecovery is 1.0.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libirecovery_CFLAGS
and libirecovery_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/stek29/homebrew-idevice/issues```

When trying to install libirecovery with `--head`:
```
❯ brew install libirecovery --head
==> Cloning https://git.libimobiledevice.org/libirecovery.git
Cloning into '/Users/billy/Library/Caches/Homebrew/libirecovery--git'...
==> Checking out branch master
	Already on 'master'
Your branch is up to date with 'origin/master'.
==> ./autogen.sh
Last 15 lines from /Users/billy/Library/Logs/Homebrew/libirecovery/01.autogen.sh:
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libimobiledevice-glue-1.0 >= 1.0.0... no
configure: error: Package requirements (libimobiledevice-glue-1.0 >= 1.0.0) were not met:

No package 'libimobiledevice-glue-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables limd_glue_CFLAGS
and limd_glue_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://docs.brew.sh/Troubleshooting```

**Comment by stek29** [comment]
should work now, try `brew update && brew install stek29/idevice/libirecovery`
no need to install `HEAD`

**Comment by stek29** [comment]
(make sure you're installing with full path `stek29/idevice/libirecovery` and not just `libirecovery` - homebrew core has older release of libirecovery and can be picked over this tap)

**Comment by InternalLoss** [comment]
All good now - thank you!
