### ISSUE TITLE
Can't install futurerestore-s0uthwest

### ISSUE THREAD

**Issue by stek29** [stek29/homebrew-idevice#4]
If you have tried to install futurerestore-s0uthwest from idevice tap at the point of time @s0uthwest had broken submodules, you'll get `make: *** No targets specified and no makefile found.  Stop.` error when trying to install/upgrade.

homebrew fails to sync submodules if cached version had broken submodules, so you'd have to do `rm -rf ~/Library/Caches/Homebrew/futurerestore-s0uthwest--git` so it re-fetches everything.

**Comment by Diatrus** [comment]
@stek29 Added your cask today, and I'm getting this error. Tried re-fetching everything.

**Comment by leftyfl1p** [comment]
Can confirm I've received the same error after adding the cask today, re-fetch workaround doesn't change anything.

**Comment by stek29** [comment]
it's not cask but tap, btw :)

Are you getting exact same error? Does `brew cleanup` + `rm -rf  ~/Library/Caches/Homebrew/*` help?

It works perfectly fine for me and I'm unable to reproduce the issue.

Try `brew install futurerestore-s0uthwest --debug`, and when you get the error, type `shell`, and check `git status` -- are submodules ok?

**Comment by leftyfl1p** [comment]
None of those helped but I finally figured out that it's because brew was looking for `libimobiledevice-1.0 >= 1.2.1` and the homebrew package is currently at 1.2.0 so --head was required which in itself was [an annoyance to install](https://github.com/flutter/flutter/issues/22595).

**Comment by Diatrus** [comment]
Can confirm @leftyfl1p identified the problem.

**Comment by stek29** [comment]
oh, well, yeah, you need --HEAD version of libimobiledevice/usbmuxd
