### ISSUE TITLE
tsschecker formula

### ISSUE THREAD

**Issue by maenpaa24** [stek29/homebrew-idevice#52]
Hi, tsschecker formula seems to be broken. The error says

`Error: Operation already in progress for libplist.formula`

I have noticed that in addition to stek29's libplist formula it installs libplist core's formula, so I guess it is related. I have checked the code for stek29's libplist formula and it only says it depends on stek29/idevice/libplist, I do not know where is the thing that triggers the installation of hombrew core's libplist formula. Libplist released version 2.3.0 recently, it might be the reason because it used to build it fine not too long ago.

**Comment by stek29** [comment]
should be working now after #61

**Comment by maenpaa24** [comment]
It does work. Thank you.
