### ISSUE TITLE
futurerestore-s0uthwes error due to libimg4tool.a

### ISSUE THREAD

**Issue by riotdream** [stek29/homebrew-idevice#6]
| => brew install futurerestore-s0uthwest
==> Installing futurerestore-s0uthwest from stek29/idevice
==> Cloning https://github.com/s0uthwest/futurerestore.git
Updating /Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git
==> Checking out revision b8af2bc72bcb54fe1e32084cad1644ef95682b84
HEAD is now at b8af2bc TSSChecker: fix win64 compiling
HEAD is now at b8af2bc TSSChecker: fix win64 compiling
Entering 'external/idevicerestore'
Entering 'external/img4tool'
Entering 'external/tsschecker'
/Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/idevicerestore
/Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/img4tool
/Users/suzughia/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/tsschecker
==> ./autogen.sh --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/futurerestor
==> make
Last 15 lines from /Users/suzughia/Library/Logs/Homebrew/futurerestore-s0uthwest/02.make:
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -c lzssdec.c  -fno-common -DPIC -o .libs/libimg4tool_la-lzssdec.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -c img4.c  -fno-common -DPIC -o .libs/libimg4tool_la-img4.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -c img4tool.c  -fno-common -DPIC -o .libs/libimg4tool_la-img4tool.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -c lzssdec.c -o libimg4tool_la-lzssdec.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -c img4tool.c -o libimg4tool_la-img4tool.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -c img4.c -o libimg4tool_la-img4.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=CC   --mode=link clang -I/usr/local/Cellar/openssl/1.0.2q/include -DIMG4TOOL_NOMAIN -DIDEVICERESTORE_NOMAIN=1 -DIMG4TOOL_NOMAIN=1 -DTSSCHECKER_NOMAIN=1 -std=c11 -D IMG4TOOL_VERSION_COUNT=\"126\" -D IMG4TOOL_VERSION_SHA=\"94fccc6c59eea336150b687085d731f13a64e87f\" -L/usr/local/Cellar/openssl/1.0.2q/lib -lcrypto  -lcompression -o libimg4tool.la  libimg4tool_la-img4tool.lo libimg4tool_la-img4.lo libimg4tool_la-lzssdec.lo -L/usr/local/Cellar/openssl/1.0.2q/lib -lcrypto  
libtool: link: ar cru .libs/libimg4tool.a .libs/libimg4tool_la-img4tool.o .libs/libimg4tool_la-img4.o .libs/libimg4tool_la-lzssdec.o 
libtool: link: ranlib .libs/libimg4tool.a
libtool: link: ( cd ".libs" && rm -f "libimg4tool.la" && ln -s "../libimg4tool.la" "libimg4tool.la" )
make[4]: Nothing to be done for `all-am'.
Making all in external/tsschecker
make[2]: *** No rule to make target `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/stek29/homebrew-idevice/issues

________________________________________________________________________________
| => brew list
autoconf		idevicerestore		libpng			mono			readline
automake		irssi			libssh2			ncurses			rmate
cask			jpeg			libtasn1		nettle			sqlite
emacs			libffi			libtool			openssl			sshuttle
gdbm			libfragmentzip		libunistring		p11-kit			tsschecker-s0uthwest
gettext			libidn2			libusb			pcre			usbmuxd
glib			libimobiledevice	libxml2			pixman			vde
gmp			libirecovery		libzip			pkg-config		wget
gnutls			libplist		lzfse			python			xz
________________________________________________________________________________
| => brew update && brew upgrade
Already up-to-date.
________________________________________________________________________________
libimobiledevice (installed with --HEAD )
usbmuxd (installed with --HEAD )
________________________________________________________________________________

**Comment by stek29** [comment]
Try to `rm -rf ~/Library/Caches/Homebrew/futurerestore-s0uthwest--git`

**Comment by stek29** [comment]
And install again after that.

**Comment by riotdream** [comment]
you're the man! its works! I've cancelled the cache but not the git clone... 

Thanks!
