### ISSUE TITLE
Unable to build due to lack of img4tool(dependency) commit

### ISSUE THREAD

**Issue by nuschpl** [stek29/homebrew-idevice#9]
There seems to be hardcoded version of img4tool as git dependency: '94fccc6c59eea336150b687085d731f13a64e87f', which doesn't exist anymore in current version of s0uthwest repo (already tried with --unshallow).

$ rm -rf ~/Library/Caches/Homebrew/futurerestore-s0uthwest--git
$ brew install stek29/idevice/futurerestore-s0uthwest
==> Installing futurerestore-s0uthwest from stek29/idevice
==> Cloning https://github.com/s0uthwest/futurerestore.git
Cloning into '/Users/user/Library/Caches/Homebrew/futurerestore-s0uthwest--git'...
==> Checking out revision b8af2bc72bcb54fe1e32084cad1644ef95682b84
Note: checking out 'b8af2bc72bcb54fe1e32084cad1644ef95682b84'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b8af2bc TSSChecker: fix win64 compiling
Submodule 'external/idevicerestore' (https://github.com/s0uthwest/idevicerestore.git) registered for path 'external/idevicerestore'
Submodule 'external/img4tool' (https://github.com/s0uthwest/img4tool.git) registered for path 'external/img4tool'
Submodule 'external/tsschecker' (https://github.com/s0uthwest/tsschecker.git) registered for path 'external/tsschecker'
Cloning into '/Users/userLibrary/Caches/Homebrew/futurerestore-s0uthwest--git/external/idevicerestore'...
Cloning into '/Users/user/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/img4tool'...
Cloning into '/Users/user/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/tsschecker'...
Submodule path 'external/idevicerestore': checked out '9db1056e311e17fb4c85ee0a602efc9c439fa9ca'
error: Server does not allow request for unadvertised object 94fccc6c59eea336150b687085d731f13a64e87f
Fetched in submodule path 'external/img4tool', but it did not contain 94fccc6c59eea336150b687085d731f13a64e87f. Direct fetching of that commit failed.
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "futurerestore-s0uthwest"
Failure while executing; `git submodule update --init --recursive` exited with 1. Here's the output:
Submodule 'external/idevicerestore' (https://github.com/s0uthwest/idevicerestore.git) registered for path 'external/idevicerestore'
Submodule 'external/img4tool' (https://github.com/s0uthwest/img4tool.git) registered for path 'external/img4tool'
Submodule 'external/tsschecker' (https://github.com/s0uthwest/tsschecker.git) registered for path 'external/tsschecker'
Cloning into '/Users/user/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/idevicerestore'...
Cloning into '/Users/user/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/img4tool'...
Cloning into '/Users/user/Library/Caches/Homebrew/futurerestore-s0uthwest--git/external/tsschecker'...
Submodule path 'external/idevicerestore': checked out '9db1056e311e17fb4c85ee0a602efc9c439fa9ca'
error: Server does not allow request for unadvertised object 94fccc6c59eea336150b687085d731f13a64e87f
Fetched in submodule path 'external/img4tool', but it did not contain 94fccc6c59eea336150b687085d731f13a64e87f. Direct fetching of that commit failed.

**Comment by stek29** [comment]
fuck @s0uthwest and his stupid commit purging shit
this is last time I fix these packages -- next time I'll just remove them.

**Comment by stek29** [comment]
fixed
